name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: junhyeong_space/codemy
          stage: main
          yaml: |
            name: self-terview
            app: python@3.11
            options:
              env:
                - name: GOOGLE_API_KEY
                  value: ${{ secrets.GOOGLE_API_KEY }}
              ports: "8080"
              start: python3 main.py
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}